---
- block:
    - name: Import Azul's public key
      apt_key:
        id: '0x219BD9C9'
        keyserver: 'hkp://keyserver.ubuntu.com:80'
        state: present

    - name: Check Azul's repository file status
      stat:
        path: /etc/apt/sources.list.d/zulu.list
      register: zulu_repo_status

    - name: Add the Azul package to the APT repository
      apt_repository:
        filename: zulu
        repo: "{{ java_apt_repo }}"
        state: present
        update_cache: yes
      when: not zulu_repo_status.stat.exists

    - name: Set Zulu package name
      set_fact:
        java_package_state: present
        java_package_name: "zulu-{{ java_major_version }}={{ java_version }}"
      when: java_version != "latest"

    - name: Install Zulu
      apt:
        cache_valid_time: "{{ apt_cache_valid_time }}"
        name: "{{ java_package_name }}"
        state: "{{ java_package_state }}"
  become: yes
  become_user: root
...