---
- block:
    - name: Import Azul's public key
      apt_key:
        id: '0x219BD9C9'
        keyserver: 'hkp://keyserver.ubuntu.com:80'
        state: present

    - name: Add the Azul package to the APT repository
      apt_repository:
        filename: zulu
        repo: "{{ java_apt_repo }}"
        state: present
        update_cache: yes

    - name: "Set Zulu's full package name zulu-{{ java_major_version }}={{ java_version }}"
      set_fact:
        java_package_name: "zulu-{{ java_major_version }}={{ java_version }}"
      when: java_version != "latest"

    - name: Install Zulu
      apt:
        cache_valid_time: "{{ apt_cache_valid_time }}"
        name: "{{ java_package_name }}"
        state: "{{ 'latest' if java_version == 'latest' else 'present' }}"
  become: yes
  become_user: "{{ become_user }}"
...
