---
# tasks file for ansible-role-java

- name: Include linux distribution specific variables
  include_vars:
    dir: vars
    files_matching: "{{ item }}.yml"
    ignore_unknown_extensions: yes
  loop:
    - "{{ ansible_pkg_mgr }}"
    - "{{ ansible_lsb.id }}"
    - "{{ ansible_lsb.id }}-{{ ansible_lsb.major_release }}"
    - "{{ ansible_lsb.id }}-{{ ansible_lsb.release }}"

- name: Run package manager specific tasks
  include_tasks: "{{ ansible_pkg_mgr }}-{{ java_vendor }}.yml"

- name: Setup JAVA_HOME environment variable at "{{ java_home }}"
  lineinfile:
    line: "JAVA_HOME={{ java_home }}"
    path: /etc/environment
    regexp: '^JAVA_HOME='
  become: yes
  become_user: "{{ become_user }}"
...
