---
# tasks file for ansible-role-java

- name: Include package manager specific vars
  include_vars: "{{ ansible_pkg_mgr }}.yml"
  ignore_errors: yes

- name: Include distribution specific vars
  include_vars: "{{ ansible_distribution }}.yml"
  ignore_errors: yes

- name: Run package manager specific tasks
  include_tasks: "{{ ansible_pkg_mgr }}-{{ java_vendor }}.yml"

- block:
    - name: Setup JAVA_HOME environment variable
      blockinfile:
        block: |
          export JAVA_HOME={{ java_home }}
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK to set java environment variables"
        path: /etc/bash.bashrc
  become: yes
  become_user: root
...
