---
# tasks file for ansible-role-java

- name: Include OS specific vars
  include_vars: "{{ item }}.yml"
  with_items:
    - "{{ ansible_pkg_mgr }}"
    - "{{ ansible_distribution | lower }}"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}"
  ignore_errors: yes

- name: Run package manager specific tasks
  include_tasks: "{{ ansible_pkg_mgr }}-{{ java_vendor }}.yml"

- name: Setup JAVA_HOME environment variable at "{{ java_home }}"
  lineinfile:
    line: "JAVA_HOME={{ java_home }}"
    path: /etc/environment
    regexp: '^JAVA_HOME='
  become: yes
  become_user: "{{ become_user }}"
...
