---
# tasks file for ansible-role-java

# Include vendor specific variables
- include_vars: "vars-{{ java_vendor }}.yml"

# Perform tasks specific for this system with the chosen vendor
- include_tasks: "setup-{{ ansible_pkg_mgr }}-{{ java_vendor }}.yml"

- block:
    - name: Setup JAVA_HOME environment variable
      blockinfile:
        block: |
          export JAVA_HOME={{ java_home }}
        dest: /etc/bash.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK to set java environment variables"
  become: yes
  become_user: root
...
