---
# tasks file for ansible-role-java

- block:
    # install appropriate package
    - include: "setup-{{ ansible_pkg_mgr }}-{{ java_vendor }}.yml"

    # setup environment
    - name: set up $JAVA_HOME
      template:
        src: java-home.sh.j2
        dest: /etc/profile.d/java-home.sh
        mode: 0644
  become: yes
...
