---
- block:
    - name: Import Azul's public key
      apt_key:
        id: 0x219BD9C9
        keyserver: hkp://keyserver.ubuntu.com:80
        state: present
    - name: Add the Azul package to the APT repository
      apt_repository:
        filename: zulu
        repo: 'deb http://repos.azulsystems.com/debian stable main'
        state: present
        update_cache: yes
    - name: Install Zulu
      apt:
        name: "zulu-{{ java_major_version }}"
        state: present
        update_cache: yes
  become: yes
...